// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using ProjectManga.Data;
using System;

namespace ProjectManga.Web.Migrations
{
    [DbContext(typeof(ProjectMangaDbContext))]
    partial class ProjectMangaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("ProjectManga.Domain.Download.Models.DownloadRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("FromChapterPart");

                    b.Property<int?>("FromPage");

                    b.Property<string>("Sid");

                    b.Property<int?>("ToChapter");

                    b.Property<int?>("ToChapterPart");

                    b.Property<int?>("ToPage");

                    b.HasKey("Id");

                    b.ToTable("DownloadRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
